In [2]:
# Imports
import pandas as pd
import numpy as np

In [10]:
# On récupere le df final utilisé pour le machine learning
df = pd.read_csv('../../ressources/df_final.csv', sep=';')
df

,tconst,primaryTitle,title,frenchTitle,startYear,genres,production_countries,runtimeMinutes,revenue,tagline,overview,id,averageRating,numVotes,actor1,actor2,actor3,directors
0,tt0006864,Intolerance,Intolerance: Love's Struggle Throughout the Ages,Intolérance,1916,"History, Drama",US,163,4000000.0,The Cruel Hand of Intolerance,"The story of a poor young woman, separated by ...",3059,7.7,17434,Lillian Gish,Robert Harron,Mae Marsh,D.W. Griffith
1,tt0009968,Broken Blossoms,Broken Blossoms,Le lys brisé,1919,"Drama, Romance",US,90,2400000.0,A Tale of Forbidden Love,The love story of an abused English girl and a...,899,7.2,11483,Lillian Gish,Richard Barthelmess,Donald Crisp,D.W. Griffith
2,tt0010307,J'accuse!,J'accuse,J'accuse,1919,"History, War, Drama, Horror, Romance",FR,166,0.0,NaN,"The story of two men, one married, the other t...",70804,7.7,2249,Romuald Joubé,Maxime Desjardins,Séverin-Mars,Abel Gance
3,tt0010418,Male and Female,Male and Female,L'admirable Crichton,1919,"Drama, Adventure, Fantasy",US,116,0.0,CECIL B DE MILLE'S SUBLIME MIRROR OF LIFE,When an aristocratic family and their servants...,53761,7.0,2032,Thomas Meighan,Theodore Roberts,Raymond Hatton,Cecil B. DeMille
4,tt0011439,The Mark of Zorro,The Mark of Zorro,Le signe de Zorro,1920,"Adventure, Drama, Western, Action, Romance",US,79,0.0,Here's the picture in which the world's greate...,Don Diego Vega pretends to be an indolent fop ...,42657,7.0,2946,Douglas Fairbanks,Marguerite De La Motte,Noah Beery,Fred Niblo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17266,tt9902160,Herself,Herself,Herself,2020,Drama,"IE,GB",97,0.0,Life under construction,Struggling to provide her daughters with a saf...,653708,7.0,5127,Molly McCann,Clare Dunne,Ruby Rose O'Hara,Phyllida Lloyd
17267,tt9904802,Enemy Lines,Enemy Lines,Enemy Lines,2020,"Drama, Action, War",GB,92,0.0,Courage has no border.,"In the frozen, war torn landscape of occupied ...",679796,4.6,2045,Ed Westwick,John Hannah,Tom Wisdom,Anders Banke
17268,tt9907782,The Cursed,The Cursed,Eight for Silver,2021,"Mystery, Fantasy, Horror",US,111,4588389.0,NaN,"In the late 19th century, a brutal land baron ...",630392,6.2,20425,Boyd Holbrook,Kelly Reilly,Alistair Petrie,Sean Ellis
17269,tt9908390,Le lion,The Lion,Le lion,2020,Comedy,FR,95,0.0,NaN,A psychiatric hospital patient pretends to be ...,589970,5.5,1522,Dany Boon,Philippe Katerine,Anne Serra,Ludovic Colbeau-Justin
17270,tt9916362,Coven,Coven,Les sorcières d'Akelarre,2020,"History, Drama","AR,ES,FR",92,0.0,NaN,"French Basque Country, year 1609. The men of a...",655187,6.4,6053,Amaia Aberasturi,Alex Brendemühl,Daniel Fanego,Pablo Agüero

In [13]:
# Pour l'affichage on garde les colonnes suivantes:
# tconst / id / frenchTitle / primaryTitle / averageRating / runtimeMinutes / genres / startYear / overview / acteurs / directors 
df = df[['tconst', 'id', 'frenchTitle', 'primaryTitle', 'averageRating', 'runtimeMinutes', 'genres', 'startYear', 'overview', 'actor1', 'actor2', 'actor3', 'directors']]

df

,tconst,id,frenchTitle,primaryTitle,averageRating,runtimeMinutes,genres,startYear,overview,actor1,actor2,actor3,directors
0,tt0006864,3059,Intolérance,Intolerance,7.7,163,"History, Drama",1916,"The story of a poor young woman, separated by ...",Lillian Gish,Robert Harron,Mae Marsh,D.W. Griffith
1,tt0009968,899,Le lys brisé,Broken Blossoms,7.2,90,"Drama, Romance",1919,The love story of an abused English girl and a...,Lillian Gish,Richard Barthelmess,Donald Crisp,D.W. Griffith
2,tt0010307,70804,J'accuse,J'accuse!,7.7,166,"History, War, Drama, Horror, Romance",1919,"The story of two men, one married, the other t...",Romuald Joubé,Maxime Desjardins,Séverin-Mars,Abel Gance
3,tt0010418,53761,L'admirable Crichton,Male and Female,7.0,116,"Drama, Adventure, Fantasy",1919,When an aristocratic family and their servants...,Thomas Meighan,Theodore Roberts,Raymond Hatton,Cecil B. DeMille
4,tt0011439,42657,Le signe de Zorro,The Mark of Zorro,7.0,79,"Adventure, Drama, Western, Action, Romance",1920,Don Diego Vega pretends to be an indolent fop ...,Douglas Fairbanks,Marguerite De La Motte,Noah Beery,Fred Niblo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17266,tt9902160,653708,Herself,Herself,7.0,97,Drama,2020,Struggling to provide her daughters with a saf...,Molly McCann,Clare Dunne,Ruby Rose O'Hara,Phyllida Lloyd
17267,tt9904802,679796,Enemy Lines,Enemy Lines,4.6,92,"Drama, Action, War",2020,"In the frozen, war torn landscape of occupied ...",Ed Westwick,John Hannah,Tom Wisdom,Anders Banke
17268,tt9907782,630392,Eight for Silver,The Cursed,6.2,111,"Mystery, Fantasy, Horror",2021,"In the late 19th century, a brutal land baron ...",Boyd Holbrook,Kelly Reilly,Alistair Petrie,Sean Ellis
17269,tt9908390,589970,Le lion,Le lion,5.5,95,Comedy,2020,A psychiatric hospital patient pretends to be ...,Dany Boon,Philippe Katerine,Anne Serra,Ludovic Colbeau-Justin
17270,tt9916362,655187,Les sorcières d'Akelarre,Coven,6.4,92,"History, Drama",2020,"French Basque Country, year 1609. The men of a...",Amaia Aberasturi,Alex Brendemühl,Daniel Fanego,Pablo Agüero

In [14]:
# On concatene  les colonnes acteurs pour en faire une seule
df['acteurs'] = df['actor1'] + ', ' + df['actor2'] + ', ' + df['actor3']
# On supprime les colonnes inutiles
df = df.drop(columns=['actor1', 'actor2', 'actor3'])
df

C:\Users\User\AppData\Local\Temp\ipykernel_29724\52039359.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['acteurs'] = df['actor1'] + ', ' + df['actor2'] + ', ' + df['actor3']

,tconst,id,frenchTitle,primaryTitle,averageRating,runtimeMinutes,genres,startYear,overview,directors,acteurs
0,tt0006864,3059,Intolérance,Intolerance,7.7,163,"History, Drama",1916,"The story of a poor young woman, separated by ...",D.W. Griffith,"Lillian Gish, Robert Harron, Mae Marsh"
1,tt0009968,899,Le lys brisé,Broken Blossoms,7.2,90,"Drama, Romance",1919,The love story of an abused English girl and a...,D.W. Griffith,"Lillian Gish, Richard Barthelmess, Donald Crisp"
2,tt0010307,70804,J'accuse,J'accuse!,7.7,166,"History, War, Drama, Horror, Romance",1919,"The story of two men, one married, the other t...",Abel Gance,"Romuald Joubé, Maxime Desjardins, Séverin-Mars"
3,tt0010418,53761,L'admirable Crichton,Male and Female,7.0,116,"Drama, Adventure, Fantasy",1919,When an aristocratic family and their servants...,Cecil B. DeMille,"Thomas Meighan, Theodore Roberts, Raymond Hatton"
4,tt0011439,42657,Le signe de Zorro,The Mark of Zorro,7.0,79,"Adventure, Drama, Western, Action, Romance",1920,Don Diego Vega pretends to be an indolent fop ...,Fred Niblo,"Douglas Fairbanks, Marguerite De La Motte, Noa..."
...,...,...,...,...,...,...,...,...,...,...,...
17266,tt9902160,653708,Herself,Herself,7.0,97,Drama,2020,Struggling to provide her daughters with a saf...,Phyllida Lloyd,"Molly McCann, Clare Dunne, Ruby Rose O'Hara"
17267,tt9904802,679796,Enemy Lines,Enemy Lines,4.6,92,"Drama, Action, War",2020,"In the frozen, war torn landscape of occupied ...",Anders Banke,"Ed Westwick, John Hannah, Tom Wisdom"
17268,tt9907782,630392,Eight for Silver,The Cursed,6.2,111,"Mystery, Fantasy, Horror",2021,"In the late 19th century, a brutal land baron ...",Sean Ellis,"Boyd Holbrook, Kelly Reilly, Alistair Petrie"
17269,tt9908390,589970,Le lion,Le lion,5.5,95,Comedy,2020,A psychiatric hospital patient pretends to be ...,Ludovic Colbeau-Justin,"Dany Boon, Philippe Katerine, Anne Serra"
17270,tt9916362,655187,Les sorcières d'Akelarre,Coven,6.4,92,"History, Drama",2020,"French Basque Country, year 1609. The men of a...",Pablo Agüero,"Amaia Aberasturi, Alex Brendemühl, Daniel Fanego"

In [ ]:
# On va devoir récuperer les colonnes qui nous manquent pour l'affichage:
# affiche / bande-annonce / classification

In [ ]:
# Récuperer des id:
# https://api.themoviedb.org/3/movie/{movie_id}/external_ids

In [ ]:
# Récuperer les videos:
# https://api.themoviedb.org/3/movie/{movie_id}/videos?language=fr-FR"