Exploration Fichiers CSV

In [1]:
import pandas as pd
import gdown

In [2]:
# Liens vers les fichiers de données IMDb
# Ces fichiers sont disponibles en téléchargement sur le site IMDb
link_title_basics = "https://datasets.imdbws.com/title.basics.tsv.gz"
link_title_akas = "https://datasets.imdbws.com/title.akas.tsv.gz"
link_title_crew = "https://datasets.imdbws.com/title.crew.tsv.gz"
#link_title_episode = "https://datasets.imdbws.com/title.episode.tsv.gz" -> non utilisé car pas de séries
link_title_principals = "https://datasets.imdbws.com/title.principals.tsv.gz"
link_title_ratings = "https://datasets.imdbws.com/title.ratings.tsv.gz"
link_name_basics = "https://datasets.imdbws.com/name.basics.tsv.gz"
link_tmdb = "https://drive.google.com/file/d/1VB5_gl1fnyBDzcIOXZ5vUSbCY68VZN1v/view"

In [3]:
# Fichier TMDB
file_id = "1VB5_gl1fnyBDzcIOXZ5vUSbCY68VZN1v"
output = "../ressources/tmdb_movies.csv"
#gdown.download(id=file_id,
#               output=output,
#               quiet=False,      # affiche la barre de progression
#               fuzzy=True)

In [4]:
df_name_basics = pd.read_csv(link_name_basics, sep="\t", low_memory=False)
df_title_principals = pd.read_csv(link_title_principals, sep="\t", low_memory=False)
df_title_crew = pd.read_csv(link_title_crew, sep="\t", low_memory=False)
df_title_akas = pd.read_csv(link_title_akas, sep="\t", low_memory=False)
df_title_ratings = pd.read_csv(link_title_ratings, sep="\t", low_memory=False)
df_tmdb = pd.read_csv(output, low_memory=False)
df_title_basics = pd.read_csv(link_title_basics, sep="\t", low_memory=False)

In [5]:
# Copy
df_title_basics_copy = df_title_basics.copy()

In [6]:
# Trie des genres
# Remplacer NaN et \\N par "Unknown"
df_title_basics_copy["genres"] = df_title_basics_copy["genres"].str.replace("\\N", "Unknown", regex=False)
df_title_basics_copy["genres"] = df_title_basics_copy["genres"].fillna("Unknown")

# Genre non gardé : Documentary / Short / News / Talk-show / Game-Show / Reality-TV / Adult 
# On les enlève de la liste des genres
list_genre_to_drop = ["Documentary", "Short", "News", "Talk-show", "Game-Show", "Reality-TV", "Adult"]
regex_pattern = '|'.join(map(lambda x: f'({x})', list_genre_to_drop))
df_title_basics_copy = df_title_basics_copy[~df_title_basics_copy['genres'].str.contains(regex_pattern, regex=True)]

C:\Users\User\AppData\Local\Temp\ipykernel_1552\634574185.py:10: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_title_basics_copy = df_title_basics_copy[~df_title_basics_copy['genres'].str.contains(regex_pattern, regex=True)]

In [7]:
# Verifier les différents types de films
df_title_basics_copy['titleType'].unique()

# On récupere uniquement les films
df_title_basics_copy = df_title_basics_copy[df_title_basics_copy['titleType'] == 'movie']

# On enlève les films pour adultes
df_title_basics_copy = df_title_basics_copy[df_title_basics_copy['isAdult'] == '0']

# On enlève les films sans titre
df_title_basics_copy['primaryTitle'] = df_title_basics_copy['primaryTitle'].fillna('None.')

#display(df_title_basics_copy[df_title_basics_copy['primaryTitle'].isna() == False].head(3))

In [8]:
# Jointure entre df_title_basics_copy et df_tmdb, clé communune : tconst et imdb_id
df_merged = pd.merge(df_title_basics_copy, df_tmdb, left_on='tconst', right_on='imdb_id', how='left')

# On enlève les colonnes inutiles
df_merged = df_merged.drop(columns=['isAdult', 'originalTitle', 'endYear', 'adult', 'budget', 'homepage', 'imdb_id', 'original_title', 'titleType', 'runtime'])

# On transforme les colonnes 'runtimeMinutes', 'id', 'popularity', 'runtime', 'revenue', 'vote_average', 'vote_count' en numérique
df_merged['runtimeMinutes'] = pd.to_numeric(df_merged['runtimeMinutes'], errors='coerce', downcast='signed').astype('Int64')  
df_merged['id'] = pd.to_numeric(df_merged['id'], errors='coerce', downcast='integer').astype('Int64')  
df_merged['popularity'] = pd.to_numeric(df_merged['popularity'], errors='coerce', downcast='signed')
df_merged['revenue'] = pd.to_numeric(df_merged['revenue'], errors='coerce', downcast='signed')
df_merged['vote_average'] = pd.to_numeric(df_merged['vote_average'], errors='coerce', downcast='signed')
df_merged['vote_count'] = pd.to_numeric(df_merged['vote_count'], errors='coerce', downcast='signed').astype('Int64')

# On transforme la colonne 'startYear' en datetime
df_title_basics_copy['startYear'] = pd.to_numeric(df_title_basics_copy['startYear'], errors='coerce',downcast ='signed').astype('Int64')
df_merged['startYear'] = pd.to_datetime(df_merged['startYear'], format='%Y', errors='coerce').dt.to_period('Y')

# On transforme la colonne 'release_date' en datetime
df_merged['release_date'] = pd.to_datetime(df_merged['release_date'], format='%Y-%m-%d', errors='coerce').dt.date

# On filtre la colonne 'production_country' pour ne garder que les pays de production souhaités : USA,FR,GB
df_filtered = df_merged[df_merged['production_countries'].str.contains('USA|GB|FR|US', na=False)]

# On réorganise les colonnes : 'tconst', 'primaryTitle', 'title', 'startYear', 'release_date', 'genre_x', 'genre_y', 'production_countries', 'runtimeMinutes', 'vote_average', 'vote_count', 'popularity', 'revenue', 'tagline', 'overview', 'id'
df_filtered = df_filtered[['tconst', 'primaryTitle', 'title', 'startYear', 'release_date', 'genres_x', 'genres_y', 'production_countries', 'runtimeMinutes', 'vote_average', 'vote_count', 'popularity', 'revenue', 'tagline', 'overview', 'id']]

# Renomme la colonne 'genres_x' en 'genres_df_title_basics' et genres_y en 'genres_df_tmdb'
df_filtered = df_filtered.rename(columns={'genres_x': 'genres_df_title_basics', 'genres_y': 'genres_df_tmdb'})

#df_filtered

In [9]:
# Création d'un df pour les titres de films en francais et suppression des colonnes inutiles
df_title_akas_clean = df_title_akas.copy()
df_title_akas_clean = df_title_akas_clean.drop(columns=['ordering', 'language', 'types', 'attributes', 'isOriginalTitle'])

# Affiche les titres de la région FR
df_title_akas_clean = df_title_akas_clean[df_title_akas_clean['region'] == 'FR']

# Changement de la colonne 'title' en 'frenchTitle'
df_title_akas_clean = df_title_akas_clean.rename(columns={'title': 'frenchTitle'})

#df_title_akas_clean.head(3)

In [10]:
# Jointure entre df_filtered et df_title_akas_clean, clé communune : tconst et titleId
df_filtered_french_title = pd.merge(df_filtered, df_title_akas_clean, left_on='tconst', right_on='titleId', how='left')

#  Suppression des colonnes titleId, region
df_filtered_french_title = df_filtered_french_title.drop(columns=['titleId', 'region'], axis=1)

# Si frenchTitle est NaN, on remplace par primaryTitle
df_filtered_french_title['frenchTitle'] = df_filtered_french_title['frenchTitle'].fillna(df_filtered_french_title['primaryTitle'])

# Enleve les '[]' et les ' dans genres_df_tmdb
df_filtered_french_title['genres_df_tmdb'] = df_filtered_french_title['genres_df_tmdb'].apply(lambda x: str(x).replace('[','').replace(']','').replace('\'', '').replace(' ',''))

# Enleve les '[]' et les ' dans production_countries
df_filtered_french_title['production_countries'] = df_filtered_french_title['production_countries'].apply(lambda x: str(x).replace('[','').replace(']','').replace('\'', '').replace(' ',''))

# Concatene les colonnes 'genres_df_title_basics' et 'genres_df_tmdb' en une seule colonne 'genres' et supprime les termes en doublon de la colonne 'genres'
df_filtered_french_title['genres'] = df_filtered_french_title.apply(lambda x: ', '.join(set(str(x['genres_df_title_basics']).split(',') + str(x['genres_df_tmdb']).split(','))), axis=1)    

# Supprime les colonnes 'genres_df_title_basics' et 'genres_df_tmdb'
df_filtered_french_title = df_filtered_french_title.drop(columns=['genres_df_title_basics', 'genres_df_tmdb'], axis=1)

# Range les colonnes
df_filtered_french_title = df_filtered_french_title[['tconst', 'primaryTitle',  'title', 'frenchTitle','startYear', 'genres', 'production_countries', 'runtimeMinutes', 'vote_average', 'vote_count', 'popularity', 'revenue', 'tagline', 'overview', 'id']]

#df_filtered_french_title.head(3)

In [11]:
# Jointure entre df_filtered_french_title et df_title_ratings, clé commune : tconst
# On garde les colonnes 'tconst', 'averageRating', 'numVotes' et on supprime les colonnes 'vote_average', 'vote_count' et 'popularity' de df_filtered_french_title qui viennent de df_tmdb
df_filtered_ratings = pd.merge(df_filtered_french_title, df_title_ratings, left_on='tconst', right_on='tconst', how='left')
df_filtered_ratings = df_filtered_ratings.drop(columns=['vote_average', 'vote_count', 'popularity'], axis=1)
df_filtered_ratings['numVotes'] = df_filtered_ratings['numVotes'].astype('Int64')

# On enlève les films sans note
df_filtered_ratings = df_filtered_ratings[df_filtered_ratings['averageRating'].notna()]

# On enlève les films sortis avant 1990 dont la note est inférieure à 7. Et tout les films avec moins de 1000 votes
df_filtered_ratings = df_filtered_ratings[~((df_filtered_ratings['startYear'].dt.year < 1990) & (df_filtered_ratings['averageRating'] < 7))]
df_filtered_ratings = df_filtered_ratings[~(df_filtered_ratings['numVotes'] < 1500)]

# Créer un filtre pour la colonne runtimeMinutes qui n'affiche que les films de plus de 60 minutes et de moins de 250 minutes
df_filtered_ratings = df_filtered_ratings[(df_filtered_ratings['runtimeMinutes'] > 60) & (df_filtered_ratings['runtimeMinutes'] < 250)]

df_filtered_ratings

,tconst,primaryTitle,title,frenchTitle,startYear,genres,production_countries,runtimeMinutes,revenue,tagline,overview,id,averageRating,numVotes
233,tt0006864,Intolerance,Intolerance: Love's Struggle Throughout the Ages,Intolérance,1916,"History, Drama",US,163,4000000.0,The Cruel Hand of Intolerance,"The story of a poor young woman, separated by ...",3059,7.7,17434
631,tt0009968,Broken Blossoms,Broken Blossoms,Le lys brisé,1919,"Drama, Romance",US,90,2400000.0,A Tale of Forbidden Love,The love story of an abused English girl and a...,899,7.2,11483
669,tt0010307,J'accuse!,J'accuse,J'accuse,1919,"History, War, Drama, Horror, Romance",FR,166,0.0,NaN,"The story of two men, one married, the other t...",70804,7.7,2249
685,tt0010418,Male and Female,Male and Female,L'admirable Crichton,1919,"Drama, Adventure, Fantasy",US,116,0.0,CECIL B DE MILLE'S SUBLIME MIRROR OF LIFE,When an aristocratic family and their servants...,53761,7.0,2032
817,tt0011439,The Mark of Zorro,The Mark of Zorro,Le signe de Zorro,1920,"Adventure, Drama, Western, Action, Romance",US,79,0.0,Here's the picture in which the world's greate...,Don Diego Vega pretends to be an indolent fop ...,42657,7.0,2946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69946,tt9904802,Enemy Lines,Enemy Lines,Enemy Lines,2020,"Drama, Action, War",GB,92,0.0,Courage has no border.,"In the frozen, war torn landscape of occupied ...",679796,4.6,2045
69947,tt9907782,The Cursed,The Cursed,Eight for Silver,2021,"Mystery, Fantasy, Horror",US,111,4588389.0,NaN,"In the late 19th century, a brutal land baron ...",630392,6.2,20425
69948,tt9907782,The Cursed,The Cursed,The Cursed,2021,"Mystery, Fantasy, Horror",US,111,4588389.0,NaN,"In the late 19th century, a brutal land baron ...",630392,6.2,20425
69949,tt9908390,Le lion,The Lion,Le lion,2020,Comedy,FR,95,0.0,NaN,A psychiatric hospital patient pretends to be ...,589970,5.5,1522
69952,tt9916362,Coven,Coven,Les sorcières d'Akelarre,2020,"History, Drama","AR,ES,FR",92,0.0,NaN,"French Basque Country, year 1609. The men of a...",655187,6.4,6053

In [12]:
# Suppression des doublons de la colonne 'tconst'
df_filtered_ratings_test = df_filtered_ratings.drop_duplicates(subset=['tconst'])
df_filtered_ratings_test

,tconst,primaryTitle,title,frenchTitle,startYear,genres,production_countries,runtimeMinutes,revenue,tagline,overview,id,averageRating,numVotes
233,tt0006864,Intolerance,Intolerance: Love's Struggle Throughout the Ages,Intolérance,1916,"History, Drama",US,163,4000000.0,The Cruel Hand of Intolerance,"The story of a poor young woman, separated by ...",3059,7.7,17434
631,tt0009968,Broken Blossoms,Broken Blossoms,Le lys brisé,1919,"Drama, Romance",US,90,2400000.0,A Tale of Forbidden Love,The love story of an abused English girl and a...,899,7.2,11483
669,tt0010307,J'accuse!,J'accuse,J'accuse,1919,"History, War, Drama, Horror, Romance",FR,166,0.0,NaN,"The story of two men, one married, the other t...",70804,7.7,2249
685,tt0010418,Male and Female,Male and Female,L'admirable Crichton,1919,"Drama, Adventure, Fantasy",US,116,0.0,CECIL B DE MILLE'S SUBLIME MIRROR OF LIFE,When an aristocratic family and their servants...,53761,7.0,2032
817,tt0011439,The Mark of Zorro,The Mark of Zorro,Le signe de Zorro,1920,"Adventure, Drama, Western, Action, Romance",US,79,0.0,Here's the picture in which the world's greate...,Don Diego Vega pretends to be an indolent fop ...,42657,7.0,2946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69944,tt9902160,Herself,Herself,Herself,2020,Drama,"IE,GB",97,0.0,Life under construction,Struggling to provide her daughters with a saf...,653708,7.0,5127
69946,tt9904802,Enemy Lines,Enemy Lines,Enemy Lines,2020,"Drama, Action, War",GB,92,0.0,Courage has no border.,"In the frozen, war torn landscape of occupied ...",679796,4.6,2045
69947,tt9907782,The Cursed,The Cursed,Eight for Silver,2021,"Mystery, Fantasy, Horror",US,111,4588389.0,NaN,"In the late 19th century, a brutal land baron ...",630392,6.2,20425
69949,tt9908390,Le lion,The Lion,Le lion,2020,Comedy,FR,95,0.0,NaN,A psychiatric hospital patient pretends to be ...,589970,5.5,1522
69952,tt9916362,Coven,Coven,Les sorcières d'Akelarre,2020,"History, Drama","AR,ES,FR",92,0.0,NaN,"French Basque Country, year 1609. The men of a...",655187,6.4,6053

In [13]:
df_filtered_ratings_test[df_filtered_ratings_test['tconst'] == 'tt0848228']

,tconst,primaryTitle,title,frenchTitle,startYear,genres,production_countries,runtimeMinutes,revenue,tagline,overview,id,averageRating,numVotes
43943,tt0848228,The Avengers,The Avengers,Avengers,2012,"ScienceFiction, Adventure, Action, Sci-Fi",US,143,1.518816e+09,Some assembly required.,When an unexpected enemy emerges and threatens...,24428,8.0,1510866

In [14]:
df_cast = df_title_principals.copy()
# On merge df_cast avec df_name_basics pour ajouter le nom des acteurs
df_cast = df_cast.merge(df_name_basics[['nconst', 'primaryName']], on='nconst', how='left')
df_cast = df_cast.sort_values(by=['tconst', 'ordering'])

df_cast[df_cast['tconst'] == 'tt0848228']

,tconst,ordering,nconst,category,job,characters,primaryName
9745477,tt0848228,1,nm0000375,actor,\N,"[""Tony Stark""]",Robert Downey Jr.
9745478,tt0848228,2,nm0000375,actor,\N,"[""Iron Man""]",Robert Downey Jr.
9745479,tt0848228,3,nm0262635,actor,\N,"[""Steve Rogers""]",Chris Evans
9745480,tt0848228,4,nm0262635,actor,\N,"[""Captain America""]",Chris Evans
9745481,tt0848228,5,nm0424060,actress,\N,"[""Natasha Romanoff""]",Scarlett Johansson
9745482,tt0848228,6,nm0424060,actress,\N,"[""Black Widow""]",Scarlett Johansson
9745483,tt0848228,7,nm0719637,actor,\N,"[""Clint Barton""]",Jeremy Renner
9745484,tt0848228,8,nm0719637,actor,\N,"[""Hawkeye""]",Jeremy Renner
9745485,tt0848228,9,nm0749263,actor,\N,"[""Bruce Banner""]",Mark Ruffalo
9745486,tt0848228,10,nm0749263,actor,\N,"[""The Hulk""]",Mark Ruffalo
9745487,tt0848228,11,nm1165110,actor,\N,"[""Thor""]",Chris Hemsworth
9745488,tt0848228,12,nm1089991,actor,\N,"[""Loki""]",Tom Hiddleston
9745489,tt0848228,13,nm0163988,actor,\N,"[""Agent Phil Coulson""]",Clark Gregg
9745490,tt0848228,14,nm1130627,actress,\N,"[""Agent Maria Hill""]",Cobie Smulders
9745491,tt0848228,15,nm0001745,actor,\N,"[""Selvig""]",Stellan Skarsgård
9745492,tt0848228,16,nm0923736,director,\N,\N,Joss Whedon
9745493,tt0848228,17,nm0923736,writer,screenplay,\N,Joss Whedon
9745494,tt0848228,18,nm0672015,writer,story,\N,Zak Penn
9745495,tt0848228,19,nm0270559,producer,producer,\N,Kevin Feige
9745496,tt0848228,20,nm0006293,composer,\N,\N,Alan Silvestri
9745497,tt0848228,21,nm0568974,cinematographer,director of photography,\N,Seamus McGarvey
9745498,tt0848228,22,nm0285701,editor,\N,\N,Jeffrey Ford
9745499,tt0848228,23,nm0489809,editor,\N,\N,Lisa Lassek
9745500,tt0848228,24,nm0278168,casting_director,casting_director,\N,Sarah Finn
9745501,tt0848228,25,nm0384900,casting_director,\N,\N,Randi Hiller
9745502,tt0848228,26,nm0157913,production_designer,\N,\N,James Chinlund

In [15]:
# On enleve les acteurs en doublons pour un tconst
df_cast = df_cast.drop_duplicates(subset=['tconst', 'nconst'])

In [16]:
# On garde uniquement les 3 premiers acteurs par tconst
df_cast = df_cast.groupby('tconst').head(3)

# On garde les colonnes 'tconst', 'primaryName' 
df_cast = df_cast[['tconst', 'primaryName']]

df_cast[df_cast['tconst'] == 'tt0848228']

            tconst         primaryName
9745477  tt0848228   Robert Downey Jr.
9745479  tt0848228         Chris Evans
9745481  tt0848228  Scarlett Johansson

In [17]:
# On fait une colonne pour chaque acteur : Actor1, Actor2, Actor3
df_cast['actor_num'] = df_cast.groupby('tconst').cumcount() + 1
df_cast_pivot = df_cast.pivot(index='tconst', columns='actor_num', values='primaryName')
df_cast_pivot.columns = [f'actor{i}' for i in df_cast_pivot.columns]

df_cast_pivot = df_cast_pivot.reset_index()

df_cast_pivot[df_cast_pivot['tconst'] == 'tt0848228']

           tconst             actor1       actor2              actor3
809174  tt0848228  Robert Downey Jr.  Chris Evans  Scarlett Johansson

In [18]:
# On concatene df_filtered_ratings_test et df_cast_pivot sur la colonne tconst
df_actors = pd.merge(df_filtered_ratings_test, df_cast_pivot, on='tconst', how='left')

In [ ]:
# On exporte le dataframe avec les 3 colonnes d'acteurs
#df_actors.to_csv('../ressources/df_actor_col.csv', index=False)

In [20]:
# On va récuperer les réalisateurs dans df_title_crew
df_crew = df_title_crew.copy()

df_directors = df_crew[['tconst', 'directors']]

df_directors

             tconst   directors
0         tt0000001   nm0005690
1         tt0000002   nm0721526
2         tt0000003   nm0721526
3         tt0000004   nm0721526
4         tt0000005   nm0005690
...             ...         ...
11693903  tt9916848   nm1485677
11693904  tt9916850   nm1485677
11693905  tt9916852   nm1485677
11693906  tt9916856  nm10538645
11693907  tt9916880   nm0996406

[11693908 rows x 2 columns]

In [21]:
df_directors['directors'] = df_directors['directors'].str.split(',')
# On explode la colonne 'directors' pour avoir un réalisateur par ligne
df_directors = df_directors.explode('directors')

# On merge df_directors avec df_name_basics pour ajouter le nom des réalisateurs
df_directors = df_directors.merge(df_name_basics[['nconst', 'primaryName']], left_on='directors', right_on='nconst', how='left')

C:\Users\User\AppData\Local\Temp\ipykernel_1552\1144542651.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_directors['directors'] = df_directors['directors'].str.split(',')

In [24]:
# On remplace les NaN par 'Unknown'
df_directors['primaryName'] = df_directors['primaryName'].fillna('Unknown')

# On garde uniquement les 3 premiers réalisateurs par tconst
df_directors = df_directors.groupby('tconst').head(2)

# On garde les colonnes 'tconst' et 'primaryName'
df_directors_final = df_directors[['tconst', 'primaryName']].drop_duplicates()

df_directors_final = df_directors_final.groupby('tconst')['primaryName'].apply(lambda x: ', '.join(x)).reset_index()

# On renomme la colonne 'primaryName' en 'directors'
df_directors_final = df_directors_final.rename(columns={'primaryName': 'directors'})

df_directors_final.head(10)

      tconst                            directors
0  tt0000001                 William K.L. Dickson
1  tt0000002                        Émile Reynaud
2  tt0000003                        Émile Reynaud
3  tt0000004                        Émile Reynaud
4  tt0000005                 William K.L. Dickson
5  tt0000006                 William K.L. Dickson
6  tt0000007  William K.L. Dickson, William Heise
7  tt0000008                 William K.L. Dickson
8  tt0000009                      Alexander Black
9  tt0000010                        Louis Lumière

In [ ]:
# On merge df_actors et df_directors_final sur la colonne tconst
df_final = pd.merge(df_actors, df_directors_final, on='tconst', how='left')

df_final.head(10)

,tconst,primaryTitle,title,frenchTitle,startYear,genres,production_countries,runtimeMinutes,revenue,tagline,overview,id,averageRating,numVotes,actor1,actor2,actor3,directors
0,tt0006864,Intolerance,Intolerance: Love's Struggle Throughout the Ages,Intolérance,1916,"History, Drama",US,163,4000000.0,The Cruel Hand of Intolerance,"The story of a poor young woman, separated by ...",3059,7.7,17434,Lillian Gish,Robert Harron,Mae Marsh,D.W. Griffith
1,tt0009968,Broken Blossoms,Broken Blossoms,Le lys brisé,1919,"Drama, Romance",US,90,2400000.0,A Tale of Forbidden Love,The love story of an abused English girl and a...,899,7.2,11483,Lillian Gish,Richard Barthelmess,Donald Crisp,D.W. Griffith
2,tt0010307,J'accuse!,J'accuse,J'accuse,1919,"History, War, Drama, Horror, Romance",FR,166,0.0,NaN,"The story of two men, one married, the other t...",70804,7.7,2249,Romuald Joubé,Maxime Desjardins,Séverin-Mars,Abel Gance
3,tt0010418,Male and Female,Male and Female,L'admirable Crichton,1919,"Drama, Adventure, Fantasy",US,116,0.0,CECIL B DE MILLE'S SUBLIME MIRROR OF LIFE,When an aristocratic family and their servants...,53761,7.0,2032,Thomas Meighan,Theodore Roberts,Raymond Hatton,Cecil B. DeMille
4,tt0011439,The Mark of Zorro,The Mark of Zorro,Le signe de Zorro,1920,"Adventure, Drama, Western, Action, Romance",US,79,0.0,Here's the picture in which the world's greate...,Don Diego Vega pretends to be an indolent fop ...,42657,7.0,2946,Douglas Fairbanks,Marguerite De La Motte,Noah Beery,Fred Niblo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17266,tt9902160,Herself,Herself,Herself,2020,Drama,"IE,GB",97,0.0,Life under construction,Struggling to provide her daughters with a saf...,653708,7.0,5127,Molly McCann,Clare Dunne,Ruby Rose O'Hara,Phyllida Lloyd
17267,tt9904802,Enemy Lines,Enemy Lines,Enemy Lines,2020,"Drama, Action, War",GB,92,0.0,Courage has no border.,"In the frozen, war torn landscape of occupied ...",679796,4.6,2045,Ed Westwick,John Hannah,Tom Wisdom,Anders Banke
17268,tt9907782,The Cursed,The Cursed,Eight for Silver,2021,"Mystery, Fantasy, Horror",US,111,4588389.0,NaN,"In the late 19th century, a brutal land baron ...",630392,6.2,20425,Boyd Holbrook,Kelly Reilly,Alistair Petrie,Sean Ellis
17269,tt9908390,Le lion,The Lion,Le lion,2020,Comedy,FR,95,0.0,NaN,A psychiatric hospital patient pretends to be ...,589970,5.5,1522,Dany Boon,Philippe Katerine,Anne Serra,Ludovic Colbeau-Justin
17270,tt9916362,Coven,Coven,Les sorcières d'Akelarre,2020,"History, Drama","AR,ES,FR",92,0.0,NaN,"French Basque Country, year 1609. The men of a...",655187,6.4,6053,Amaia Aberasturi,Alex Brendemühl,Daniel Fanego,Pablo Agüero

In [ ]:
# On exporte le dataframe final
df_final.to_csv('../ressources/df_final.csv', index=False, sep=';')